# Source: https://hub.docker.com/r/linuxserver/freshrss#:~:text=must%20be%20provided.-,docker%2Dcompose,-(recommended%2C%20click
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ~/docker/freshrss/config:/config
    ports:
      - 8010:80
    restart: unless-stopped
